"""Added user_id to Patient model

Revision ID: 97a2ffd95d5d
Revises: 8e23b4297329
Create Date: 2025-12-23 16:05:13.692531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a2ffd95d5d'
down_revision = '8e23b4297329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_patient_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('fk_patient_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
